# Generated by Django 5.2.13 on 2026-04-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status_historicalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('editor', 'Editor'), ('author', 'Author'), ('viewer', 'Viewer')], default='author', max_length=10),
        ),
    ]
