# Generated by Django 5.2.13 on 2026-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Caminho (URL)')),
                ('method', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário')),
                ('exception_type', models.CharField(max_length=255, verbose_name='Tipo de Exceção')),
                ('exception_message', models.TextField(verbose_name='Mensagem de Erro')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Log de Erro',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-created_at'],
            },
        ),
    ]
