# Generated by Django 5.2.13 on 2026-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
