# Generated by Django 5.2.13 on 2026-04-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authorprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
